/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class PrimeiroAno extends javax.swing.JFrame {
    int finalizar=0;
    String terminar[]= new String[3];
    /**
     * Creates new form PrimeiroAno
     */
    public PrimeiroAno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listening = new javax.swing.JButton();
        reading = new javax.swing.JButton();
        grammar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botao_finalizar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Questões do 1° ano");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        listening.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        listening.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/Listening.png"))); // NOI18N
        listening.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        listening.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listeningActionPerformed(evt);
            }
        });

        reading.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        reading.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/Reading1.png"))); // NOI18N
        reading.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reading.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readingActionPerformed(evt);
            }
        });

        grammar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        grammar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/Grammar.png"))); // NOI18N
        grammar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        grammar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grammarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Selecione a questão");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        botao_finalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botao_finalizar.setText("Terminar");
        botao_finalizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                botao_finalizarFocusLost(evt);
            }
        });
        botao_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_finalizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(grammar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(reading, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(listening, javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(botao_finalizar, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(listening, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reading, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(grammar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botao_finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void listeningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listeningActionPerformed
  
        if(terminar[0].equals("terminou")){
            JOptionPane.showMessageDialog(this,"Você já realizou este exercício","Alerta",JOptionPane.ERROR_MESSAGE); 
        }
        else{
            Tela_ListeningPrimeiroAno a = new Tela_ListeningPrimeiroAno();
            a.setVisible(true);
            this.setVisible(false);
        }
        
    }//GEN-LAST:event_listeningActionPerformed

    private void readingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readingActionPerformed
  
        if(terminar[1].equals("terminou")){
            JOptionPane.showMessageDialog(this,"Você já realizou este exercício","Alerta",JOptionPane.ERROR_MESSAGE); 
        }
        else{
            Tela_Reading_Questoes_PrimeiroAno b = new Tela_Reading_Questoes_PrimeiroAno();
            b.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_readingActionPerformed

    private void botao_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_finalizarActionPerformed
        if(finalizar==0){
            JOptionPane.showMessageDialog(this,"Clique novamente no botão 'finalizar' para ver o resultado. NÃO será possível fazer a prova novamente","Alerta",JOptionPane.WARNING_MESSAGE); 
        }
        else{
            Tela_Finalizar a = new Tela_Finalizar();
            a.setVisible(true);
            this.setVisible(false);            
        }
        finalizar++;

    }//GEN-LAST:event_botao_finalizarActionPerformed

    private void botao_finalizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_botao_finalizarFocusLost
        finalizar=0;
    }//GEN-LAST:event_botao_finalizarFocusLost

    private void grammarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grammarActionPerformed
     
        if(terminar[2].equals("terminou")){
            JOptionPane.showMessageDialog(this,"Você já realizou este exercício","Alerta",JOptionPane.ERROR_MESSAGE); 
        }
        else{
            Tela_Grammar_Primeiro_Ano abrir = new Tela_Grammar_Primeiro_Ano();
            abrir.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_grammarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        verificar_listening();
        
    }//GEN-LAST:event_formWindowOpened
    private void verificar_listening(){
        
        File arquivo = new File("Terminou_o_listening.txt");
        try{
            FileReader ler = new FileReader(arquivo);
            BufferedReader ler_arquivo= new BufferedReader(ler);
            terminar[0]=ler_arquivo.readLine();
            
        }catch(IOException ex){
            
        }         
        verificar_reading();
    }
    private void verificar_reading(){

        File arquivo = new File("Terminou_o_reading.txt");
        try{
            FileReader ler = new FileReader(arquivo);
            BufferedReader ler_arquivo= new BufferedReader(ler);
            terminar[1]=ler_arquivo.readLine();
            
        }catch(IOException ex){
            
        }    
        verificar_grammar();
    }
    private void verificar_grammar(){

        File arquivo = new File("Terminou_o_grammar.txt");
        try{
            FileReader ler = new FileReader(arquivo);
            BufferedReader ler_arquivo= new BufferedReader(ler);
            terminar[2]=ler_arquivo.readLine();
            
        }catch(IOException ex){
            
        }         
        exibir_mensagem();
    }
    private void exibir_mensagem(){
        if(terminar [0].equals("nao") & terminar [1].equals("nao") & terminar [2].equals("nao") ){
            JOptionPane.showMessageDialog(this, "Tenha atenção ao terminar um campo, pois não será possível refazê-lo.");
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrimeiroAno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botao_finalizar;
    private javax.swing.JButton grammar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listening;
    private javax.swing.JButton reading;
    // End of variables declaration//GEN-END:variables
}
