/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author mathe
 */
public class Tela_Editar_Grammar_PrimeiroAno extends javax.swing.JFrame {
    String questoes[]= new String [21];
    int fechamento=0;
    /**
     * Creates new form Editar_Grammar_PrimeiroAno
     */
    public Tela_Editar_Grammar_PrimeiroAno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        enunciado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        enunciado1 = new javax.swing.JTextField();
        r1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        enunciado2 = new javax.swing.JTextField();
        r2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        enunciado3 = new javax.swing.JTextField();
        r3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        enunciado4 = new javax.swing.JTextField();
        r4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        enunciado5 = new javax.swing.JTextField();
        r5 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        enunciado6 = new javax.swing.JTextField();
        r6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        enunciado7 = new javax.swing.JTextField();
        r7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        enunciado8 = new javax.swing.JTextField();
        r8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        enunciado9 = new javax.swing.JTextField();
        r9 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        enunciado10 = new javax.swing.JTextField();
        r10 = new javax.swing.JTextField();
        salvar_finalizar = new javax.swing.JButton();
        sair_sem_salvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        interrog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Enunciado:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 860, -1));

        enunciado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enunciado.setText("Carregando");
        getContentPane().add(enunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 36, 860, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Questão 1:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 86, -1, -1));

        enunciado1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enunciado1.setText("Carregando");
        getContentPane().add(enunciado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 116, 860, -1));

        r1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        r1.setText("Carregando");
        getContentPane().add(r1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 860, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Questão 2:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 204, 860, -1));

        enunciado2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enunciado2.setText("Carregando");
        getContentPane().add(enunciado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 234, 860, -1));

        r2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        r2.setText("Carregando");
        getContentPane().add(r2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 272, 860, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Questão 3:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 322, 860, -1));

        enunciado3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enunciado3.setText("Carregando");
        getContentPane().add(enunciado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 352, 860, -1));

        r3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        r3.setText("Carregando");
        getContentPane().add(r3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 390, 860, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("Questão 4:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 440, 860, -1));

        enunciado4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enunciado4.setText("Carregando");
        getContentPane().add(enunciado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 470, 860, -1));

        r4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        r4.setText("Carregando");
        getContentPane().add(r4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 508, 860, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel6.setText("Questão 5:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 558, 860, -1));

        enunciado5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enunciado5.setText("Carregando");
        getContentPane().add(enunciado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 588, 860, -1));

        r5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        r5.setText("Carregando");
        getContentPane().add(r5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 626, 860, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setText("Questão 6:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 86, -1, -1));

        enunciado6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enunciado6.setText("Carregando");
        getContentPane().add(enunciado6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 116, 860, -1));

        r6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        r6.setText("Carregando");
        getContentPane().add(r6, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 154, 860, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setText("Questão 7:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 204, -1, -1));

        enunciado7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enunciado7.setText("Carregando");
        getContentPane().add(enunciado7, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 234, 860, -1));

        r7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        r7.setText("Carregando");
        getContentPane().add(r7, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 272, 860, -1));

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setText("Questão 8:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 322, -1, -1));

        enunciado8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enunciado8.setText("Carregando");
        getContentPane().add(enunciado8, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 352, 860, -1));

        r8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        r8.setText("Carregando");
        getContentPane().add(r8, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 390, 860, -1));

        jLabel10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel10.setText("Questão 9:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 440, -1, -1));

        enunciado9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enunciado9.setText("Carregando");
        getContentPane().add(enunciado9, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 470, 860, -1));

        r9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        r9.setText("Carregando");
        getContentPane().add(r9, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 508, 860, -1));

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Questão 10:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 558, -1, -1));

        enunciado10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        enunciado10.setText("Carregando");
        getContentPane().add(enunciado10, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 588, 860, -1));

        r10.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        r10.setText("Carregando");
        getContentPane().add(r10, new org.netbeans.lib.awtextra.AbsoluteConstraints(884, 626, 860, -1));

        salvar_finalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        salvar_finalizar.setText("Salvar");
        salvar_finalizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                salvar_finalizarFocusLost(evt);
            }
        });
        salvar_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_finalizarActionPerformed(evt);
            }
        });
        getContentPane().add(salvar_finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 30, 110, -1));

        sair_sem_salvar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sair_sem_salvar.setText("Sair sem salvar");
        sair_sem_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_sem_salvarActionPerformed(evt);
            }
        });
        getContentPane().add(sair_sem_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 30, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 30, -1, -1));

        interrog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/interrogacao2.png"))); // NOI18N
        interrog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interrogActionPerformed(evt);
            }
        });
        getContentPane().add(interrog, new org.netbeans.lib.awtextra.AbsoluteConstraints(1710, 0, 50, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void salvar_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_finalizarActionPerformed
        if(fechamento==0){
            questoes[1]=enunciado1.getText();
            questoes[2]=enunciado2.getText();
            questoes[3]=enunciado3.getText();
            questoes[4]=enunciado4.getText();
            questoes[5]=enunciado5.getText();
            questoes[6]=enunciado6.getText();
            questoes[7]=enunciado7.getText();
            questoes[8]=enunciado8.getText();
            questoes[9]=enunciado9.getText();
            questoes[10]=enunciado10.getText();

            questoes[11]=r1.getText();
            questoes[12]=r2.getText();
            questoes[13]=r3.getText();
            questoes[14]=r4.getText();
            questoes[15]=r5.getText();
            questoes[16]=r6.getText();
            questoes[17]=r7.getText();
            questoes[18]=r8.getText();
            questoes[19]=r9.getText();
            questoes[20]=r10.getText();
            
            questoes[0]=enunciado.getText();
            try {
                apagar();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Editar_Grammar_PrimeiroAno.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            fechamento ++;
        }
        else{
            sair_sem_salvarActionPerformed(evt);
        }
    }//GEN-LAST:event_salvar_finalizarActionPerformed
    private void apagar() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();

        for(int cont=1;cont<=21;cont++){
            String query = ("DELETE FROM tb_grammar_primeiro_ano WHERE id="+cont);    
            PreparedStatement preparedStmt = bd.prepareStatement(query);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd);        
        reiniciar_ai();
        
        //DELETE FROM tb_grammar_primeiro_ano WHERE id=x
    }
    private void reiniciar_ai() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = ("alter table tb_grammar_primeiro_ano AUTO_INCREMENT = 1");    
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt.execute();
        Tela_Inicial.closeConnection(bd);        
        salvar_bd();
    }
    private void salvar_bd() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = "insert into tb_grammar_primeiro_ano (questoes_respostas) values (?)";
        PreparedStatement preparedStmt;
        preparedStmt = bd.prepareStatement(query);
        for(int cont=0;cont<21;cont++){
            preparedStmt.setString (1, questoes[cont]);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd);
        JOptionPane.showMessageDialog(this,"Salvo com sucesso.","Salvamento",JOptionPane.INFORMATION_MESSAGE);
        salvar_finalizar.setText("Finalizar");
    }
    private void sair_sem_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_sem_salvarActionPerformed
        Tela_Editar_PrimeiroAno abrir= new Tela_Editar_PrimeiroAno();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sair_sem_salvarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            pegar_bd();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Editar_Grammar_PrimeiroAno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void salvar_finalizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salvar_finalizarFocusLost
        fechamento=0;
        salvar_finalizar.setText("Salvar");
    }//GEN-LAST:event_salvar_finalizarFocusLost

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tela_Visualizar_Grammar_Primeiro_Ano1 abrir = new Tela_Visualizar_Grammar_Primeiro_Ano1();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void interrogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interrogActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Lembre-se de salvar tudo antes de mudar a tela.");
    }//GEN-LAST:event_interrogActionPerformed
    private void pegar_bd() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        int cont=0;
        String query;
        query = "SELECT * FROM tb_grammar_primeiro_ano";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt = bd.prepareStatement(query);
        ResultSet rs = preparedStmt.executeQuery();
        while(rs.next()){ 
            questoes[cont]=rs.getString("questoes_respostas");
            cont++;
        }
        rs.close();
	preparedStmt.close();
        Tela_Inicial.closeConnection(bd);
        organizar_questoes();
    }
    private void organizar_questoes(){
        enunciado1.setText(questoes[1]);
        enunciado2.setText(questoes[2]);
        enunciado3.setText(questoes[3]);
        enunciado4.setText(questoes[4]);
        enunciado5.setText(questoes[5]);
        enunciado6.setText(questoes[6]);
        enunciado7.setText(questoes[7]);
        enunciado8.setText(questoes[8]);
        enunciado9.setText(questoes[9]);
        enunciado10.setText(questoes[10]);
        
        r1.setText(questoes[11]);
        r2.setText(questoes[12]);
        r3.setText(questoes[13]);
        r4.setText(questoes[14]);
        r5.setText(questoes[15]);
        r6.setText(questoes[16]);
        r7.setText(questoes[17]);
        r8.setText(questoes[18]);
        r9.setText(questoes[19]);
        r10.setText(questoes[20]);
        
        enunciado.setText(questoes[0]);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Grammar_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Grammar_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Grammar_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Grammar_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Editar_Grammar_PrimeiroAno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField enunciado;
    private javax.swing.JTextField enunciado1;
    private javax.swing.JTextField enunciado10;
    private javax.swing.JTextField enunciado2;
    private javax.swing.JTextField enunciado3;
    private javax.swing.JTextField enunciado4;
    private javax.swing.JTextField enunciado5;
    private javax.swing.JTextField enunciado6;
    private javax.swing.JTextField enunciado7;
    private javax.swing.JTextField enunciado8;
    private javax.swing.JTextField enunciado9;
    private javax.swing.JButton interrog;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField r1;
    private javax.swing.JTextField r10;
    private javax.swing.JTextField r2;
    private javax.swing.JTextField r3;
    private javax.swing.JTextField r4;
    private javax.swing.JTextField r5;
    private javax.swing.JTextField r6;
    private javax.swing.JTextField r7;
    private javax.swing.JTextField r8;
    private javax.swing.JTextField r9;
    private javax.swing.JButton sair_sem_salvar;
    private javax.swing.JButton salvar_finalizar;
    // End of variables declaration//GEN-END:variables

    private PreparedStatement PreparedStatement(String query) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
