/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static proeficiencia.Tela_Inicial.closeConnection;

/**
 *
 * @author mathe
 */
public class Tela_Editar_Reading_PrimeiroAno extends javax.swing.JFrame {
    int cont_fechamento=0;
    int cont_fechamento2=0;
    String texto[]= new String [17];
    String respostas_do_professor[]= new String [5];
    String[] questoes= new String[25];
    public Tela_Editar_Reading_PrimeiroAno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        enunciado = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        linha2 = new javax.swing.JTextField();
        linha1 = new javax.swing.JTextField();
        linha4 = new javax.swing.JTextField();
        linha3 = new javax.swing.JTextField();
        linha8 = new javax.swing.JTextField();
        linha7 = new javax.swing.JTextField();
        linha6 = new javax.swing.JTextField();
        linha5 = new javax.swing.JTextField();
        linha15 = new javax.swing.JTextField();
        linha14 = new javax.swing.JTextField();
        linha13 = new javax.swing.JTextField();
        linha16 = new javax.swing.JTextField();
        linha9 = new javax.swing.JTextField();
        linha10 = new javax.swing.JTextField();
        linha11 = new javax.swing.JTextField();
        linha12 = new javax.swing.JTextField();
        jBsalvar_texto = new javax.swing.JButton();
        sair_sem_salvar_texto = new javax.swing.JButton();
        visualizador1 = new javax.swing.JButton();
        interrog1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Alt_2_1 = new javax.swing.JRadioButton();
        Alt_2_2 = new javax.swing.JRadioButton();
        Alt_2_3 = new javax.swing.JRadioButton();
        Alt_2_4 = new javax.swing.JRadioButton();
        A_2_1 = new javax.swing.JTextField();
        A_2_2 = new javax.swing.JTextField();
        A_2_3 = new javax.swing.JTextField();
        A_3_4 = new javax.swing.JTextField();
        A_4_3 = new javax.swing.JTextField();
        Q3 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Q1 = new javax.swing.JLabel();
        Enunciado1 = new javax.swing.JTextField();
        Alt_1_1 = new javax.swing.JRadioButton();
        A_4_4 = new javax.swing.JTextField();
        Enunciado3 = new javax.swing.JTextField();
        Q4 = new javax.swing.JLabel();
        Alt_3_1 = new javax.swing.JRadioButton();
        Enunciado4 = new javax.swing.JTextField();
        Alt_3_2 = new javax.swing.JRadioButton();
        Alt_4_1 = new javax.swing.JRadioButton();
        Alt_3_3 = new javax.swing.JRadioButton();
        Alt_4_2 = new javax.swing.JRadioButton();
        Alt_3_4 = new javax.swing.JRadioButton();
        Alt_4_3 = new javax.swing.JRadioButton();
        A_3_1 = new javax.swing.JTextField();
        Alt_4_4 = new javax.swing.JRadioButton();
        A_3_2 = new javax.swing.JTextField();
        A_4_1 = new javax.swing.JTextField();
        A_3_3 = new javax.swing.JTextField();
        A_4_2 = new javax.swing.JTextField();
        Alt_5_4 = new javax.swing.JRadioButton();
        A_5_1 = new javax.swing.JTextField();
        A_5_2 = new javax.swing.JTextField();
        A_5_3 = new javax.swing.JTextField();
        A_5_4 = new javax.swing.JTextField();
        Q5 = new javax.swing.JLabel();
        Enunciado5 = new javax.swing.JTextField();
        Alt_1_2 = new javax.swing.JRadioButton();
        Alt_5_1 = new javax.swing.JRadioButton();
        Alt_1_3 = new javax.swing.JRadioButton();
        Alt_5_2 = new javax.swing.JRadioButton();
        Alt_1_4 = new javax.swing.JRadioButton();
        Alt_5_3 = new javax.swing.JRadioButton();
        A_1_1 = new javax.swing.JTextField();
        jBsalvar_finalizar = new javax.swing.JButton();
        A_1_2 = new javax.swing.JTextField();
        A_1_3 = new javax.swing.JTextField();
        A_1_4 = new javax.swing.JTextField();
        A_2_4 = new javax.swing.JTextField();
        Q2 = new javax.swing.JLabel();
        Enunciado2 = new javax.swing.JTextField();
        sair_sem_salvar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        interrog2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Enunciado:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 10, -1, -1));

        enunciado.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        enunciado.setText("Carregando");
        jPanel1.add(enunciado, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 6, 1403, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Escreva o texto nos campos abaixo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 50, -1, -1));

        linha2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha2.setText("Carregando");
        linha2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha2KeyTyped(evt);
            }
        });
        jPanel1.add(linha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 118, 1646, -1));

        linha1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linha1.setText("Carregando");
        linha1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha1KeyTyped(evt);
            }
        });
        jPanel1.add(linha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 80, 1646, -1));

        linha4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha4.setText("Carregando");
        linha4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha4KeyTyped(evt);
            }
        });
        jPanel1.add(linha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, 1646, -1));

        linha3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha3.setText("Carregando");
        linha3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha3KeyTyped(evt);
            }
        });
        jPanel1.add(linha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 156, 1646, -1));

        linha8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha8.setText("Carregando");
        linha8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha8KeyTyped(evt);
            }
        });
        jPanel1.add(linha8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 346, 1646, -1));

        linha7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha7.setText("Carregando");
        linha7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha7KeyTyped(evt);
            }
        });
        jPanel1.add(linha7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 308, 1646, -1));

        linha6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha6.setText("Carregando");
        linha6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha6KeyTyped(evt);
            }
        });
        jPanel1.add(linha6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 270, 1646, -1));

        linha5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha5.setText("Carregando");
        linha5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha5KeyTyped(evt);
            }
        });
        jPanel1.add(linha5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 232, 1646, -1));

        linha15.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha15.setText("Carregando");
        linha15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha15KeyTyped(evt);
            }
        });
        jPanel1.add(linha15, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 612, 1646, -1));

        linha14.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha14.setText("Carregando");
        linha14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha14KeyTyped(evt);
            }
        });
        jPanel1.add(linha14, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 574, 1646, -1));

        linha13.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha13.setText("Carregando");
        linha13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha13KeyTyped(evt);
            }
        });
        jPanel1.add(linha13, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 536, 1646, -1));

        linha16.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha16.setText("Carregando");
        linha16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha16KeyTyped(evt);
            }
        });
        jPanel1.add(linha16, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 650, 1646, -1));

        linha9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha9.setText("Carregando");
        linha9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha9KeyTyped(evt);
            }
        });
        jPanel1.add(linha9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 384, 1646, -1));

        linha10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha10.setText("Carregando");
        linha10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha10KeyTyped(evt);
            }
        });
        jPanel1.add(linha10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 422, 1646, -1));

        linha11.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha11.setText("Carregando");
        linha11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha11KeyTyped(evt);
            }
        });
        jPanel1.add(linha11, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 460, 1646, -1));

        linha12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linha12.setText("Carregando");
        linha12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                linha12KeyTyped(evt);
            }
        });
        jPanel1.add(linha12, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 498, 1646, -1));

        jBsalvar_texto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBsalvar_texto.setText("Salvar");
        jBsalvar_texto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBsalvar_textoFocusLost(evt);
            }
        });
        jBsalvar_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvar_textoActionPerformed(evt);
            }
        });
        jPanel1.add(jBsalvar_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1540, 700, 110, -1));

        sair_sem_salvar_texto.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sair_sem_salvar_texto.setText("Sair sem salvar");
        sair_sem_salvar_texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_sem_salvar_textoActionPerformed(evt);
            }
        });
        jPanel1.add(sair_sem_salvar_texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1369, 700, -1, -1));

        visualizador1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        visualizador1.setText("Visualizar");
        visualizador1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visualizador1ActionPerformed(evt);
            }
        });
        jPanel1.add(visualizador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1236, 700, -1, -1));

        interrog1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/interrogacao2.png"))); // NOI18N
        interrog1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interrog1ActionPerformed(evt);
            }
        });
        jPanel1.add(interrog1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1570, 0, 50, 50));

        jTabbedPane1.addTab("Texto", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(Alt_2_1);
        Alt_2_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 326, -1, -1));

        buttonGroup2.add(Alt_2_2);
        Alt_2_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 362, -1, -1));

        buttonGroup2.add(Alt_2_3);
        Alt_2_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 398, -1, -1));

        buttonGroup2.add(Alt_2_4);
        Alt_2_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 432, -1, -1));

        A_2_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_2_1.setText("jTextField1");
        A_2_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_2_1KeyTyped(evt);
            }
        });
        jPanel2.add(A_2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 324, 700, -1));

        A_2_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_2_2.setText("jTextField2");
        A_2_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_2_2KeyTyped(evt);
            }
        });
        jPanel2.add(A_2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 360, 700, -1));

        A_2_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_2_3.setText("jTextField3");
        A_2_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_2_3KeyTyped(evt);
            }
        });
        jPanel2.add(A_2_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 396, 700, -1));

        A_3_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_3_4.setText("jTextField4");
        A_3_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_3_4KeyTyped(evt);
            }
        });
        jPanel2.add(A_3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 700, -1));

        A_4_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_4_3.setText("jTextField3");
        A_4_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_4_3KeyTyped(evt);
            }
        });
        jPanel2.add(A_4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 178, 700, -1));

        Q3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Q3.setText("Questão 3:");
        jPanel2.add(Q3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 480, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Altere as questoes e as respostas nesta aba. Lembre-se de escolher a alternativa correta e de salvar.");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 2, -1, -1));

        Q1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Q1.setText("Questão 1:");
        jPanel2.add(Q1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 44, -1, -1));

        Enunciado1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Enunciado1.setText("Enunciado da questão um");
        Enunciado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Enunciado1KeyTyped(evt);
            }
        });
        jPanel2.add(Enunciado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 72, 700, -1));

        buttonGroup1.add(Alt_1_1);
        Alt_1_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, -1, -1));

        A_4_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_4_4.setText("jTextField4");
        A_4_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_4_4KeyTyped(evt);
            }
        });
        jPanel2.add(A_4_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 214, 700, -1));

        Enunciado3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Enunciado3.setText("Enunciado da questão três");
        Enunciado3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Enunciado3KeyTyped(evt);
            }
        });
        jPanel2.add(Enunciado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 508, 700, -1));

        Q4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Q4.setText("Questão 4:");
        jPanel2.add(Q4, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 44, -1, -1));

        buttonGroup3.add(Alt_3_1);
        Alt_3_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 544, -1, -1));

        Enunciado4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Enunciado4.setText("Enunciado da questão 4");
        Enunciado4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Enunciado4KeyTyped(evt);
            }
        });
        jPanel2.add(Enunciado4, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 72, 700, -1));

        buttonGroup3.add(Alt_3_2);
        Alt_3_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 580, -1, -1));

        buttonGroup4.add(Alt_4_1);
        Alt_4_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 108, -1, -1));

        buttonGroup3.add(Alt_3_3);
        Alt_3_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 616, -1, -1));

        buttonGroup4.add(Alt_4_2);
        Alt_4_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 144, -1, -1));

        buttonGroup3.add(Alt_3_4);
        Alt_3_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_3_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 650, -1, -1));

        buttonGroup4.add(Alt_4_3);
        Alt_4_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_4_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 180, -1, -1));

        A_3_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_3_1.setText("jTextField1");
        A_3_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_3_1KeyTyped(evt);
            }
        });
        jPanel2.add(A_3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 542, 700, -1));

        buttonGroup4.add(Alt_4_4);
        Alt_4_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_4_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 214, -1, -1));

        A_3_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_3_2.setText("jTextField2");
        A_3_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_3_2KeyTyped(evt);
            }
        });
        jPanel2.add(A_3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 578, 700, -1));

        A_4_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_4_1.setText("jTextField1");
        A_4_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_4_1KeyTyped(evt);
            }
        });
        jPanel2.add(A_4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 106, 700, -1));

        A_3_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_3_3.setText("jTextField3");
        A_3_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_3_3KeyTyped(evt);
            }
        });
        jPanel2.add(A_3_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 614, 700, -1));

        A_4_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_4_2.setText("jTextField2");
        A_4_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_4_2KeyTyped(evt);
            }
        });
        jPanel2.add(A_4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 142, 700, -1));

        buttonGroup5.add(Alt_5_4);
        Alt_5_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_5_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 432, -1, -1));

        A_5_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_5_1.setText("jTextField1");
        A_5_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_5_1KeyTyped(evt);
            }
        });
        jPanel2.add(A_5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 324, 700, -1));

        A_5_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_5_2.setText("jTextField2");
        A_5_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_5_2KeyTyped(evt);
            }
        });
        jPanel2.add(A_5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 360, 700, -1));

        A_5_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_5_3.setText("jTextField3");
        A_5_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_5_3KeyTyped(evt);
            }
        });
        jPanel2.add(A_5_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 396, 700, -1));

        A_5_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_5_4.setText("jTextField4");
        A_5_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_5_4KeyTyped(evt);
            }
        });
        jPanel2.add(A_5_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 432, 700, -1));

        Q5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Q5.setText("Questão 5:");
        jPanel2.add(Q5, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 262, -1, -1));

        Enunciado5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Enunciado5.setText("Enunciado da questão 5");
        Enunciado5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Enunciado5KeyTyped(evt);
            }
        });
        jPanel2.add(Enunciado5, new org.netbeans.lib.awtextra.AbsoluteConstraints(931, 290, 700, -1));

        buttonGroup1.add(Alt_1_2);
        Alt_1_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 144, -1, -1));

        buttonGroup5.add(Alt_5_1);
        Alt_5_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 326, -1, -1));

        buttonGroup1.add(Alt_1_3);
        Alt_1_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 180, -1, -1));

        buttonGroup5.add(Alt_5_2);
        Alt_5_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 362, -1, -1));

        buttonGroup1.add(Alt_1_4);
        Alt_1_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 214, -1, -1));

        buttonGroup5.add(Alt_5_3);
        Alt_5_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPanel2.add(Alt_5_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(897, 398, -1, -1));

        A_1_1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_1_1.setText("jTextField1");
        A_1_1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_1_1KeyTyped(evt);
            }
        });
        jPanel2.add(A_1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 106, 700, -1));

        jBsalvar_finalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jBsalvar_finalizar.setText("Salvar");
        jBsalvar_finalizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jBsalvar_finalizarFocusLost(evt);
            }
        });
        jBsalvar_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvar_finalizarActionPerformed(evt);
            }
        });
        jPanel2.add(jBsalvar_finalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1567, 694, -1, -1));

        A_1_2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_1_2.setText("jTextField2");
        A_1_2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_1_2KeyTyped(evt);
            }
        });
        jPanel2.add(A_1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 142, 700, -1));

        A_1_3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_1_3.setText("jTextField3");
        A_1_3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_1_3KeyTyped(evt);
            }
        });
        jPanel2.add(A_1_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 178, 700, -1));

        A_1_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_1_4.setText("jTextField4");
        A_1_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_1_4KeyTyped(evt);
            }
        });
        jPanel2.add(A_1_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 214, 700, -1));

        A_2_4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        A_2_4.setText("jTextField4");
        A_2_4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                A_2_4KeyTyped(evt);
            }
        });
        jPanel2.add(A_2_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 432, 700, -1));

        Q2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Q2.setText("Questão 2:");
        jPanel2.add(Q2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 262, -1, -1));

        Enunciado2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        Enunciado2.setText("Enunciado da questão dois");
        Enunciado2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Enunciado2KeyTyped(evt);
            }
        });
        jPanel2.add(Enunciado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 700, -1));

        sair_sem_salvar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sair_sem_salvar.setText("Sair sem salvar");
        sair_sem_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sair_sem_salvarActionPerformed(evt);
            }
        });
        jPanel2.add(sair_sem_salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1364, 694, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton1.setText("Visualizar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1214, 694, -1, -1));

        interrog2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/interrogacao2.png"))); // NOI18N
        interrog2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                interrog2ActionPerformed(evt);
            }
        });
        jPanel2.add(interrog2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1592, 6, 50, 50));

        jTabbedPane1.addTab("Questões", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linha1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha1KeyTyped
        int limite=100;
        if(linha1.getText().length()>=limite){
          linha2.requestFocus();
        }
    }//GEN-LAST:event_linha1KeyTyped

    private void linha2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha2KeyTyped
        int limite=100;
        if(linha2.getText().length()>=limite){
          linha3.requestFocus();
        }
    }//GEN-LAST:event_linha2KeyTyped

    private void linha3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha3KeyTyped
        int limite=100;
        if(linha3.getText().length()>=limite){
          linha4.requestFocus();
        }   
    }//GEN-LAST:event_linha3KeyTyped

    private void linha4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha4KeyTyped
        int limite=100;
        if(linha4.getText().length()>=limite){
          linha5.requestFocus();
        }  
    }//GEN-LAST:event_linha4KeyTyped

    private void linha5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha5KeyTyped
        int limite=100;
        if(linha5.getText().length()>=limite){
          linha6.requestFocus();
        } 
    }//GEN-LAST:event_linha5KeyTyped

    private void linha6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha6KeyTyped
        int limite=100;
        if(linha6.getText().length()>=limite){
          linha7.requestFocus();
        } 
    }//GEN-LAST:event_linha6KeyTyped

    private void linha7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha7KeyTyped
        int limite=100;
        if(linha7.getText().length()>=limite){
          linha8.requestFocus();
        } 
    }//GEN-LAST:event_linha7KeyTyped

    private void linha8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha8KeyTyped
        int limite=100;
        if(linha8.getText().length()>=limite){
          linha9.requestFocus();
        } 
    }//GEN-LAST:event_linha8KeyTyped

    private void linha9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha9KeyTyped
        int limite=100;
        if(linha9.getText().length()>=limite){
          linha10.requestFocus();
        } 
    }//GEN-LAST:event_linha9KeyTyped

    private void linha10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha10KeyTyped
        int limite=100;
        if(linha10.getText().length()>=limite){
          linha11.requestFocus();
        } 
    }//GEN-LAST:event_linha10KeyTyped

    private void linha11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha11KeyTyped
        int limite=100;
        if(linha11.getText().length()>=limite){
          linha12.requestFocus();
        } 
    }//GEN-LAST:event_linha11KeyTyped

    private void linha12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha12KeyTyped
        int limite=100;
        if(linha12.getText().length()>=limite){
          linha13.requestFocus();
        } 
    }//GEN-LAST:event_linha12KeyTyped

    private void linha13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha13KeyTyped
        int limite=100;
        if(linha13.getText().length()>=limite){
          linha14.requestFocus();
        } 
    }//GEN-LAST:event_linha13KeyTyped

    private void linha14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha14KeyTyped
        int limite=100;
        if(linha14.getText().length()>=limite){
          linha15.requestFocus();
        } 
    }//GEN-LAST:event_linha14KeyTyped

    private void linha15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha15KeyTyped
        int limite=100;
        if(linha15.getText().length()>=limite){
          linha16.requestFocus();
        } 
    }//GEN-LAST:event_linha15KeyTyped

    private void linha16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linha16KeyTyped
        int limite=100;
        if(linha16.getText().length()>=limite){
          evt.consume();
        } 
    }//GEN-LAST:event_linha16KeyTyped
    
    private void jBsalvar_finalizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBsalvar_finalizarFocusLost
        cont_fechamento=0;
        jBsalvar_finalizar.setText("Salvar");
    }//GEN-LAST:event_jBsalvar_finalizarFocusLost

    private void jBsalvar_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvar_finalizarActionPerformed
        
        if(cont_fechamento==0){
            try {
                salvamento_questoes();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Editar_Reading_PrimeiroAno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            Tela_Editar_PrimeiroAno abrir = new Tela_Editar_PrimeiroAno();
            abrir.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jBsalvar_finalizarActionPerformed

    private void jBsalvar_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvar_textoActionPerformed
        if(cont_fechamento2==0){
            try {
                salvamento_doTexto();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Editar_Reading_PrimeiroAno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            Tela_Editar_PrimeiroAno abrir = new Tela_Editar_PrimeiroAno();
            abrir.setVisible(true);
            this.setVisible(false);
        } 
        
    }//GEN-LAST:event_jBsalvar_textoActionPerformed

    private void jBsalvar_textoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jBsalvar_textoFocusLost
        cont_fechamento2=0;
        jBsalvar_texto.setText("Salvar");
    }//GEN-LAST:event_jBsalvar_textoFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            carregar_ao_iniciar_TEXTO();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Editar_Reading_PrimeiroAno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void sair_sem_salvar_textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_sem_salvar_textoActionPerformed
        Tela_Editar_PrimeiroAno abrir = new Tela_Editar_PrimeiroAno();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sair_sem_salvar_textoActionPerformed

    private void sair_sem_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sair_sem_salvarActionPerformed
        Tela_Editar_PrimeiroAno abrir = new Tela_Editar_PrimeiroAno();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_sair_sem_salvarActionPerformed

    private void visualizador1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visualizador1ActionPerformed
        visualizar();
    }//GEN-LAST:event_visualizador1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        visualizar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void interrog1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interrog1ActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Lembre-se de salvar tudo antes de mudar a tela.");

    }//GEN-LAST:event_interrog1ActionPerformed

    private void interrog2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_interrog2ActionPerformed
        JOptionPane.showMessageDialog(rootPane,"Lembre-se de salvar tudo antes de mudar a tela.");
    }//GEN-LAST:event_interrog2ActionPerformed

    private void Enunciado1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enunciado1KeyTyped
        if(Enunciado1.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_Enunciado1KeyTyped

    private void A_1_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_1_1KeyTyped
        if(A_1_1.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_1_1KeyTyped

    private void A_1_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_1_2KeyTyped
        if(A_1_2.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_1_2KeyTyped

    private void A_1_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_1_3KeyTyped
        if(A_1_3.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }        
    }//GEN-LAST:event_A_1_3KeyTyped

    private void A_1_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_1_4KeyTyped
        if(A_1_4.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_1_4KeyTyped

    private void A_2_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_2_1KeyTyped
        if(A_2_1.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_2_1KeyTyped

    private void A_2_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_2_2KeyTyped
        if(A_2_2.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_2_2KeyTyped

    private void A_2_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_2_3KeyTyped
        if(A_2_3.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_2_3KeyTyped

    private void A_2_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_2_4KeyTyped
        if(A_2_4.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_2_4KeyTyped

    private void A_3_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_3_1KeyTyped
        if(A_3_1.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_3_1KeyTyped

    private void A_3_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_3_2KeyTyped
        if(A_3_2.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_3_2KeyTyped

    private void A_3_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_3_3KeyTyped
        if(A_3_3.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_3_3KeyTyped

    private void A_3_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_3_4KeyTyped
        if(A_3_4.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_3_4KeyTyped

    private void A_4_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_4_1KeyTyped
        if(A_4_1.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_4_1KeyTyped

    private void A_4_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_4_2KeyTyped
        if(A_4_2.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_4_2KeyTyped

    private void A_4_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_4_3KeyTyped
        if(A_4_3.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_4_3KeyTyped

    private void A_4_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_4_4KeyTyped
        if(A_4_4.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_4_4KeyTyped

    private void A_5_1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_5_1KeyTyped
        if(A_5_1.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_5_1KeyTyped

    private void A_5_2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_5_2KeyTyped
        if(A_5_2.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_5_2KeyTyped

    private void A_5_3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_5_3KeyTyped
        if(A_5_3.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_5_3KeyTyped

    private void A_5_4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_A_5_4KeyTyped
        if(A_5_4.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_A_5_4KeyTyped

    private void Enunciado2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enunciado2KeyTyped
        if(Enunciado2.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_Enunciado2KeyTyped

    private void Enunciado3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enunciado3KeyTyped
        if(Enunciado3.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_Enunciado3KeyTyped

    private void Enunciado4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enunciado4KeyTyped
        if(Enunciado4.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_Enunciado4KeyTyped

    private void Enunciado5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Enunciado5KeyTyped
        if(Enunciado5.getText().length()>=60){
          evt.consume();
          JOptionPane.showMessageDialog(rootPane,"Limite de 60 caracteres atingido");
        }
    }//GEN-LAST:event_Enunciado5KeyTyped
    
    private void carregar_ao_iniciar_TEXTO() throws SQLException{
        String textos[]= new String [17];
        Connection bd = Tela_Inicial.getConnection();
        int cont=0;
        String query;
        query = "SELECT * FROM tb_reading_texto_primeiro_ano";
        PreparedStatement preparedStmt;
        preparedStmt = bd.prepareStatement(query);
        ResultSet rs = preparedStmt.executeQuery();
        while(rs.next()){ 
            textos[cont]=rs.getString("texto");
            cont++;
        }
        rs.close();
        preparedStmt.close();
        Tela_Inicial.closeConnection(bd);    
        

        enunciado.setText(textos[0]);
        linha1.setText(textos[1]);
        linha2.setText(textos[2]);
        linha3.setText(textos[3]);
        linha4.setText(textos[4]);
        linha5.setText(textos[5]);
        linha6.setText(textos[6]);
        linha7.setText(textos[7]);
        linha8.setText(textos[8]);
        linha9.setText(textos[9]);
        linha10.setText(textos[10]);
        linha11.setText(textos[11]);
        linha12.setText(textos[12]);
        linha13.setText(textos[13]);
        linha14.setText(textos[14]);
        linha15.setText(textos[15]);
        linha16.setText(textos[16]);
        carregar_ao_iniciar_QUESTOES();
    }
    private void carregar_ao_iniciar_QUESTOES() throws SQLException{
       Connection bd = Tela_Inicial.getConnection();
       int cont=0,cont2=0;
       String query;
       query = "SELECT * FROM tb_readind_questoes_primeiro_ano";
       PreparedStatement preparedStmt = bd.prepareStatement(query);
       preparedStmt = bd.prepareStatement(query);
       ResultSet rs = preparedStmt.executeQuery();
        while(rs.next()){ 
            if(cont<25){
                questoes[cont]=rs.getString("questoes");
                cont++;
            }
            else{
                respostas_do_professor[cont2]=rs.getString("questoes");
                cont2++;
            }
        }
        rs.close();
	preparedStmt.close();
        Tela_Inicial.closeConnection(bd);
        setar_as_respostas_escolhidas_pelo_professor();
    }
    private void setar_as_respostas_escolhidas_pelo_professor(){
        
        if(respostas_do_professor[0].equals("1")){
        Alt_1_1.setSelected(true);
        }
        else if(respostas_do_professor[0].equals("2")){
            Alt_1_2.setSelected(true);
        }
        else if(respostas_do_professor[0].equals("3")){
            Alt_1_3.setSelected(true);
        }
        else{
            Alt_1_4.setSelected(true);
        }
        
        if(respostas_do_professor[1].equals("1")){
            Alt_2_1.setSelected(true);
        }
        else if(respostas_do_professor[1].equals("2")){
            Alt_2_2.setSelected(true);
        }
        else if(respostas_do_professor[1].equals("3")){
            Alt_2_3.setSelected(true);
        }
        else{
            Alt_2_4.setSelected(true);
        }
        
        if(respostas_do_professor[2].equals("1")){
            Alt_3_1.setSelected(true);
        }
        else if(respostas_do_professor[2].equals("2")){
            Alt_3_2.setSelected(true);
        }
        else if(respostas_do_professor[2].equals("3")){
            Alt_3_3.setSelected(true);
        }
        else{
            Alt_3_4.setSelected(true);
        }
        
        if(respostas_do_professor[3].equals("1")){
            Alt_4_1.setSelected(true);
        }
        else if(respostas_do_professor[3].equals("2")){
            Alt_4_2.setSelected(true);
        }
        else if(respostas_do_professor[3].equals("3")){
            Alt_4_3.setSelected(true);
        }
        else{
            Alt_4_4.setSelected(true);
        }
        
        if(respostas_do_professor[4].equals("1")){
            Alt_5_1.setSelected(true);
        }
        else if(respostas_do_professor[4].equals("2")){
            Alt_5_2.setSelected(true);
        }
        else if(respostas_do_professor[4].equals("3")){
            Alt_5_3.setSelected(true);
        }
        else{
            Alt_5_4.setSelected(true);
        }
        Enunciado1.setText(questoes[0]);
        Enunciado2.setText(questoes[1]);
        Enunciado3.setText(questoes[2]);
        Enunciado4.setText(questoes[3]);
        Enunciado5.setText(questoes[4]);
        A_1_1.setText(questoes[5]);   A_1_2.setText(questoes[6]);   A_1_3.setText(questoes[7]);   A_1_4.setText(questoes[8]);   
        A_2_1.setText(questoes[9]);   A_2_2.setText(questoes[10]);   A_2_3.setText(questoes[11]);   A_2_4.setText(questoes[12]);
        A_3_1.setText(questoes[13]);   A_3_2.setText(questoes[14]);   A_3_3.setText(questoes[15]);   A_3_4.setText(questoes[16]);
        A_4_1.setText(questoes[17]);   A_4_2.setText(questoes[18]);   A_4_3.setText(questoes[19]);   A_4_4.setText(questoes[20]);
        A_5_1.setText(questoes[21]);   A_5_2.setText(questoes[22]);   A_5_3.setText(questoes[23]);   A_5_4.setText(questoes[24]);
    }
    
    
    private void salvamento_doTexto () throws SQLException{
        
        texto[0]=enunciado.getText();
        texto[1]=linha1 .getText();
        texto[2]=linha2 .getText();
        texto[3]=linha3.getText();
        texto[4]=linha4 .getText();
        texto[5]=linha5 .getText();
        texto[6]=linha6 .getText();
        texto[7]=linha7 .getText();
        texto[8]=linha8 .getText();
        texto[9]=linha9 .getText();
        texto[10]=linha10 .getText();
        texto[11]=linha11 .getText();
        texto[12]=linha12 .getText();
        texto[13]=linha13 .getText();
        texto[14]=linha14 .getText();
        texto[15]=linha15 .getText();
        texto[16]=linha16 .getText();
        
        apagar_texto();
    }
    private void apagar_texto() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        for(int cont=1;cont<=17;cont++){
            String query = ("DELETE FROM tb_reading_texto_primeiro_ano WHERE id="+cont);    
            PreparedStatement preparedStmt = bd.prepareStatement(query);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd);      
        reiniciar_ai(); 
    }
    private void reiniciar_ai() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = ("alter table tb_reading_texto_primeiro_ano AUTO_INCREMENT = 1");    
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt.execute();
        Tela_Inicial.closeConnection(bd);     
        salvar_texto_bd();
    }
    private void salvar_texto_bd() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = "insert into tb_reading_texto_primeiro_ano (texto) values (?)";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        for(int cont=0;cont<17;cont++){
            preparedStmt.setString (1, texto[cont]);
            preparedStmt.execute();
        }
        closeConnection(bd); 
        JOptionPane.showMessageDialog(this,"Salvo com sucesso.","Salvamento",JOptionPane.INFORMATION_MESSAGE);
        jBsalvar_texto.setText("Finalizar");
        cont_fechamento2++;
    }
   
    
    private void salvamento_questoes() throws SQLException{
        
        questoes[0]= Enunciado1.getText();
        questoes[1]= Enunciado2.getText();
        questoes[2]= Enunciado3.getText();
        questoes[3]= Enunciado4.getText();
        questoes[4]= Enunciado5.getText(); 
        questoes[5]= A_1_1.getText();   questoes[6]= A_1_2.getText();   questoes[7]= A_1_3.getText();   questoes[8]= A_1_4.getText();
        questoes[9]= A_2_1.getText();   questoes[10]= A_2_2.getText();   questoes[11]= A_2_3.getText();   questoes[12]= A_2_4.getText();
        questoes[13]= A_3_1.getText();   questoes[14]= A_3_2.getText();   questoes[15]= A_3_3.getText();   questoes[16]= A_3_4.getText();
        questoes[17]= A_4_1.getText();   questoes[18]= A_4_2.getText();   questoes[19]= A_4_3.getText();   questoes[20]= A_4_4.getText();
        questoes[21]= A_5_1.getText();   questoes[22]= A_5_2.getText();   questoes[23]= A_5_3.getText();   questoes[24]= A_5_4.getText();

        
        if(Alt_1_1.isSelected()){
            respostas_do_professor[0]="1";
        }
        else if(Alt_1_2.isSelected()){
            respostas_do_professor[0]="2";
        }
        else if(Alt_1_3.isSelected()){
            respostas_do_professor[0]="3";
        }
        else{
            respostas_do_professor[0]="4";
        }
        
        if(Alt_2_1.isSelected()){
            respostas_do_professor[1]="1";
        }
        else if(Alt_2_2.isSelected()){
            respostas_do_professor[1]="2";
        }
        else if(Alt_2_3.isSelected()){
            respostas_do_professor[1]="3";
        }
        else{
            respostas_do_professor[1]="4";
        }
        
        if(Alt_3_1.isSelected()){
            respostas_do_professor[2]="1";
        }
        else if(Alt_3_2.isSelected()){
            respostas_do_professor[2]="2";
        }
        else if(Alt_3_3.isSelected()){
            respostas_do_professor[2]="3";
        }
        else{
            respostas_do_professor[2]="4";
        }
        
        if(Alt_4_1.isSelected()){
            respostas_do_professor[3]="1";
        }
        else if(Alt_4_2.isSelected()){
            respostas_do_professor[3]="2";
        }
        else if(Alt_4_3.isSelected()){
            respostas_do_professor[3]="3";
        }
        else{
            respostas_do_professor[3]="4";
        }
        
        if(Alt_5_1.isSelected()){
            respostas_do_professor[4]="1";
        }
        else if(Alt_5_2.isSelected()){
            respostas_do_professor[4]="2";
        }
        else if(Alt_5_3.isSelected()){
            respostas_do_professor[4]="3";
        }
        else {
            respostas_do_professor[4]="4";
        }  
        apagar2();
    }
    private void apagar2() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        for(int cont=1;cont<=30;cont++){
            String query = ("DELETE FROM tb_readind_questoes_primeiro_ano WHERE id="+cont);    
            PreparedStatement preparedStmt = bd.prepareStatement(query);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd);      
        reiniciar_ai2();
        
    }
    private void reiniciar_ai2() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = ("alter table tb_readind_questoes_primeiro_ano AUTO_INCREMENT = 1");    
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt.execute();
        Tela_Inicial.closeConnection(bd);      
        salvar_bd();
    }
    private void salvar_bd()throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = "insert into tb_readind_questoes_primeiro_ano (questoes) values (?)";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        for(int cont=0;cont<25;cont++){
            preparedStmt.setString (1, questoes[cont]);
            preparedStmt.execute();
        }
        for(int cont=0;cont<5;cont++){
            preparedStmt.setString (1, respostas_do_professor[cont]);
            preparedStmt.execute();
        }
        closeConnection(bd); 
        JOptionPane.showMessageDialog(this,"Salvo com sucesso.","Salvamento",JOptionPane.INFORMATION_MESSAGE);
        jBsalvar_finalizar.setText("Finalizar");
        cont_fechamento++;
    }   

     private void visualizar(){
         Tela_Visualizar_Reading_Questoes_PrimeiroAno1 abrir= new Tela_Visualizar_Reading_Questoes_PrimeiroAno1();
         abrir.setVisible(true);
         this.setVisible(false);
     }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Reading_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Reading_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Reading_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Editar_Reading_PrimeiroAno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Editar_Reading_PrimeiroAno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField A_1_1;
    private javax.swing.JTextField A_1_2;
    private javax.swing.JTextField A_1_3;
    private javax.swing.JTextField A_1_4;
    private javax.swing.JTextField A_2_1;
    private javax.swing.JTextField A_2_2;
    private javax.swing.JTextField A_2_3;
    private javax.swing.JTextField A_2_4;
    private javax.swing.JTextField A_3_1;
    private javax.swing.JTextField A_3_2;
    private javax.swing.JTextField A_3_3;
    private javax.swing.JTextField A_3_4;
    private javax.swing.JTextField A_4_1;
    private javax.swing.JTextField A_4_2;
    private javax.swing.JTextField A_4_3;
    private javax.swing.JTextField A_4_4;
    private javax.swing.JTextField A_5_1;
    private javax.swing.JTextField A_5_2;
    private javax.swing.JTextField A_5_3;
    private javax.swing.JTextField A_5_4;
    private javax.swing.JRadioButton Alt_1_1;
    private javax.swing.JRadioButton Alt_1_2;
    private javax.swing.JRadioButton Alt_1_3;
    private javax.swing.JRadioButton Alt_1_4;
    private javax.swing.JRadioButton Alt_2_1;
    private javax.swing.JRadioButton Alt_2_2;
    private javax.swing.JRadioButton Alt_2_3;
    private javax.swing.JRadioButton Alt_2_4;
    private javax.swing.JRadioButton Alt_3_1;
    private javax.swing.JRadioButton Alt_3_2;
    private javax.swing.JRadioButton Alt_3_3;
    private javax.swing.JRadioButton Alt_3_4;
    private javax.swing.JRadioButton Alt_4_1;
    private javax.swing.JRadioButton Alt_4_2;
    private javax.swing.JRadioButton Alt_4_3;
    private javax.swing.JRadioButton Alt_4_4;
    private javax.swing.JRadioButton Alt_5_1;
    private javax.swing.JRadioButton Alt_5_2;
    private javax.swing.JRadioButton Alt_5_3;
    private javax.swing.JRadioButton Alt_5_4;
    private javax.swing.JTextField Enunciado1;
    private javax.swing.JTextField Enunciado2;
    private javax.swing.JTextField Enunciado3;
    private javax.swing.JTextField Enunciado4;
    private javax.swing.JTextField Enunciado5;
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JTextField enunciado;
    private javax.swing.JButton interrog1;
    private javax.swing.JButton interrog2;
    private javax.swing.JButton jBsalvar_finalizar;
    private javax.swing.JButton jBsalvar_texto;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField linha1;
    private javax.swing.JTextField linha10;
    private javax.swing.JTextField linha11;
    private javax.swing.JTextField linha12;
    private javax.swing.JTextField linha13;
    private javax.swing.JTextField linha14;
    private javax.swing.JTextField linha15;
    private javax.swing.JTextField linha16;
    private javax.swing.JTextField linha2;
    private javax.swing.JTextField linha3;
    private javax.swing.JTextField linha4;
    private javax.swing.JTextField linha5;
    private javax.swing.JTextField linha6;
    private javax.swing.JTextField linha7;
    private javax.swing.JTextField linha8;
    private javax.swing.JTextField linha9;
    private javax.swing.JButton sair_sem_salvar;
    private javax.swing.JButton sair_sem_salvar_texto;
    private javax.swing.JButton visualizador1;
    // End of variables declaration//GEN-END:variables


}
