/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author mathe
 */
public class Tela_Area_do_professor extends javax.swing.JFrame {
    int id;
    /**
     * Creates new form jFArea_do_professor
     */
    public Tela_Area_do_professor() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_config = new javax.swing.JPanel();
        voltar = new javax.swing.JButton();
        mudar_senha = new javax.swing.JButton();
        painel_apagar = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cancelar = new javax.swing.JButton();
        confirmar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        primeiroAno = new javax.swing.JButton();
        segundoAno = new javax.swing.JButton();
        terceiroAno = new javax.swing.JButton();
        botao_config = new javax.swing.JButton();
        botaoInicio = new javax.swing.JButton();
        pontuacao = new javax.swing.JButton();
        abrir_painel_apagar = new javax.swing.JButton();
        resultado = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 0));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_config.setBackground(new java.awt.Color(153, 153, 153));

        voltar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        voltar.setText("Voltar");
        voltar.setPreferredSize(new java.awt.Dimension(260, 136));
        voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarActionPerformed(evt);
            }
        });

        mudar_senha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/AlterarSenha.png"))); // NOI18N
        mudar_senha.setPreferredSize(new java.awt.Dimension(260, 136));
        mudar_senha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mudar_senhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout painel_configLayout = new javax.swing.GroupLayout(painel_config);
        painel_config.setLayout(painel_configLayout);
        painel_configLayout.setHorizontalGroup(
            painel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_configLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mudar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        painel_configLayout.setVerticalGroup(
            painel_configLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_configLayout.createSequentialGroup()
                .addComponent(voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mudar_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );

        getContentPane().add(painel_config, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        painel_apagar.setBackground(new java.awt.Color(255, 153, 51));
        painel_apagar.setForeground(new java.awt.Color(255, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Ao clicar em confirmar, todos os dados de alunos serão ");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("apagados para que eles refassam a prova. ");

        cancelar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cancelar.setText("Cancelar");
        cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarActionPerformed(evt);
            }
        });

        confirmar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        confirmar.setText("Confirmar");
        confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Tenha certeza de que os dados estão salvos em um pro-");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("grama externo.");

        javax.swing.GroupLayout painel_apagarLayout = new javax.swing.GroupLayout(painel_apagar);
        painel_apagar.setLayout(painel_apagarLayout);
        painel_apagarLayout.setHorizontalGroup(
            painel_apagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_apagarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_apagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_apagarLayout.createSequentialGroup()
                        .addGroup(painel_apagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(painel_apagarLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(painel_apagarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmar)
                        .addGap(129, 129, 129))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        painel_apagarLayout.setVerticalGroup(
            painel_apagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_apagarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_apagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_apagarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 118, Short.MAX_VALUE)
                        .addGroup(painel_apagarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancelar)
                            .addComponent(confirmar)))
                    .addGroup(painel_apagarLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        getContentPane().add(painel_apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 260));

        primeiroAno.setBackground(new java.awt.Color(102, 255, 255));
        primeiroAno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        primeiroAno.setText("Primeiro Ano");
        primeiroAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroAnoActionPerformed(evt);
            }
        });
        getContentPane().add(primeiroAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 114, 196, -1));

        segundoAno.setBackground(new java.awt.Color(102, 255, 255));
        segundoAno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        segundoAno.setText("Segundo Ano");
        segundoAno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                segundoAnoActionPerformed(evt);
            }
        });
        getContentPane().add(segundoAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 196, -1));

        terceiroAno.setBackground(new java.awt.Color(102, 255, 255));
        terceiroAno.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        terceiroAno.setText("Terceiro Ano");
        getContentPane().add(terceiroAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 206, 196, -1));

        botao_config.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botao_config.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/config.png"))); // NOI18N
        botao_config.setText("Configuração");
        botao_config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botao_configActionPerformed(evt);
            }
        });
        getContentPane().add(botao_config, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, -1, -1));

        botaoInicio.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        botaoInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proeficiencia/Imagens/home.png"))); // NOI18N
        botaoInicio.setText("Inicio");
        botaoInicio.setMaximumSize(new java.awt.Dimension(50, 50));
        botaoInicio.setMinimumSize(new java.awt.Dimension(50, 50));
        botaoInicio.setPreferredSize(new java.awt.Dimension(50, 50));
        botaoInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoInicioActionPerformed(evt);
            }
        });
        getContentPane().add(botaoInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 60));

        pontuacao.setBackground(new java.awt.Color(255, 255, 102));
        pontuacao.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        pontuacao.setText("Alterar pontuação");
        pontuacao.setPreferredSize(new java.awt.Dimension(143, 40));
        pontuacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pontuacaoActionPerformed(evt);
            }
        });
        getContentPane().add(pontuacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 114, 210, -1));

        abrir_painel_apagar.setBackground(new java.awt.Color(255, 255, 102));
        abrir_painel_apagar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        abrir_painel_apagar.setText("Desbloquear alunos");
        abrir_painel_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrir_painel_apagarActionPerformed(evt);
            }
        });
        getContentPane().add(abrir_painel_apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 206, 210, -1));

        resultado.setBackground(new java.awt.Color(255, 255, 102));
        resultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        resultado.setText("Ver resultados");
        resultado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resultadoActionPerformed(evt);
            }
        });
        getContentPane().add(resultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 210, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Alterar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 84, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void segundoAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_segundoAnoActionPerformed
         JOptionPane.showMessageDialog(this,"Esta sessão está em construção, volte mais tarde","Alerta",JOptionPane.ERROR_MESSAGE);  
    }//GEN-LAST:event_segundoAnoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        painel_apagar.setVisible(false);
        painel_config.setVisible(false);
    }//GEN-LAST:event_formWindowOpened

    private void botao_configActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botao_configActionPerformed
        painel_config.setVisible(true);
        
    }//GEN-LAST:event_botao_configActionPerformed

    private void botaoInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoInicioActionPerformed
        Tela_Inicial a = new Tela_Inicial();
        a.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_botaoInicioActionPerformed

    private void primeiroAnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroAnoActionPerformed
        Tela_Editar_PrimeiroAno abrir = new Tela_Editar_PrimeiroAno();
        abrir.setVisible(true);
        this.setVisible(false);
        
    }//GEN-LAST:event_primeiroAnoActionPerformed

    private void voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarActionPerformed
        painel_config.setVisible(false);
    }//GEN-LAST:event_voltarActionPerformed

    private void mudar_senhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mudar_senhaActionPerformed
        
        Tela_de_alterar_a_senha abrir = new Tela_de_alterar_a_senha();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_mudar_senhaActionPerformed

    private void pontuacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pontuacaoActionPerformed
        Tela_Alterar_pontos abrir = new Tela_Alterar_pontos();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_pontuacaoActionPerformed

    private void abrir_painel_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrir_painel_apagarActionPerformed
        painel_apagar.setVisible(true);

    }//GEN-LAST:event_abrir_painel_apagarActionPerformed

    private void resultadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resultadoActionPerformed
        Tela_Resultados abrir = new Tela_Resultados ();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_resultadoActionPerformed

    private void confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarActionPerformed
        try {
            pegar_bd();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Area_do_professor.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_confirmarActionPerformed

    private void cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarActionPerformed
        painel_apagar.setVisible(false);
    }//GEN-LAST:event_cancelarActionPerformed
   
    private void pegar_bd() throws SQLException{
        
        Connection bd;
        String query;
        bd = Tela_Inicial.getConnection();
        query = "SELECT * FROM tb_resultado";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt = bd.prepareStatement(query);
        ResultSet rs = preparedStmt.executeQuery();
        while(rs.next()){ 
            id=rs.getInt("idResultado");
        }
        rs.close();
	preparedStmt.close();
        Tela_Inicial.closeConnection(bd);
        apagar();
    }
    
    private void apagar() throws SQLException{
        Connection bd ;
        bd = Tela_Inicial.getConnection();
        for(int cont=1;cont<=id;cont++){
            String query = ("DELETE FROM tb_resultado WHERE idResultado="+cont);    
            PreparedStatement preparedStmt = bd.prepareStatement(query);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd);        
        reiniciar_ai();
    }
    
    private void reiniciar_ai() throws SQLException{
        
        Connection bd = Tela_Inicial.getConnection();
        String query = ("alter table tb_resultado AUTO_INCREMENT = 1");    
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt.execute();
        Tela_Inicial.closeConnection(bd);        
        salvar_bd();
    }
    
    private void salvar_bd() throws SQLException{

        Connection bd = Tela_Inicial.getConnection();
        String query = "insert into tb_resultado (ra, pontos) values (?, ?)";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
            preparedStmt.setString (1,"0" );
            preparedStmt.setInt (2,0 );
            preparedStmt.execute();

        Tela_Inicial.closeConnection(bd); 
        JOptionPane.showMessageDialog(this,"Agora os alunos já podem refazer a prova.","Salvamento",JOptionPane.INFORMATION_MESSAGE);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_do_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_do_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_do_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Area_do_professor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Area_do_professor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton abrir_painel_apagar;
    private javax.swing.JButton botaoInicio;
    private javax.swing.JButton botao_config;
    private javax.swing.JButton cancelar;
    private javax.swing.JButton confirmar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton mudar_senha;
    private javax.swing.JPanel painel_apagar;
    private javax.swing.JPanel painel_config;
    private javax.swing.JButton pontuacao;
    private javax.swing.JButton primeiroAno;
    private javax.swing.JButton resultado;
    private javax.swing.JButton segundoAno;
    private javax.swing.JButton terceiroAno;
    private javax.swing.JButton voltar;
    // End of variables declaration//GEN-END:variables


}
