/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/**
 *
 * @author mathe
 */
public class Tela_Alterar_pontos extends javax.swing.JFrame {
    int cont=0;

    /**
     * Creates new form Alterar_pontos
     */
    public Tela_Alterar_pontos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        listening = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        reading = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        grammar = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        salvar_finalizar = new javax.swing.JButton();
        nao_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Dê os valores TOTAIS de cada área, ");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Listening");

        listening.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        listening.setText("...");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Reading");

        reading.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        reading.setText("...");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setText("Grammar");

        grammar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        grammar.setText("...");

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setText("sabendo que a prova vale 100.");

        salvar_finalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        salvar_finalizar.setText("Salvar");
        salvar_finalizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                salvar_finalizarFocusLost(evt);
            }
        });
        salvar_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvar_finalizarActionPerformed(evt);
            }
        });

        nao_salvar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        nao_salvar.setText("Sair sem salvar");
        nao_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nao_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(reading)
                                    .addComponent(grammar)
                                    .addComponent(listening, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                            .addComponent(jLabel5)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nao_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(salvar_finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(listening, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(reading, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(grammar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(salvar_finalizar)
                    .addComponent(nao_salvar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            pegar_bd();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Alterar_pontos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    private void salvar_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvar_finalizarActionPerformed
        if(cont==0){
            try {
                apagar();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_Alterar_pontos.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        else{
            nao_salvarActionPerformed(evt);
        }
    }//GEN-LAST:event_salvar_finalizarActionPerformed

    private void nao_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nao_salvarActionPerformed
        Tela_Area_do_professor abrir = new Tela_Area_do_professor();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_nao_salvarActionPerformed

    private void salvar_finalizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_salvar_finalizarFocusLost
        cont=0;
        salvar_finalizar.setText("Finalizar");
    }//GEN-LAST:event_salvar_finalizarFocusLost
    private void pegar_bd() throws SQLException{
        String []pontos= new String [3];
        Connection bd = Tela_Inicial.getConnection();
        int cont=0;
        String query;
        
        query = "SELECT * FROM tb_pontos";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt = bd.prepareStatement(query);
        ResultSet rs = preparedStmt.executeQuery();
        while(rs.next()){ 
            pontos[cont]=rs.getString("pontos");
            cont++;
        }

        rs.close();
	preparedStmt.close();
        Tela_Inicial.closeConnection(bd);
        listening.setText(pontos[0]);
        reading.setText(pontos[1]);
        grammar.setText(pontos[2]);
    }
    
    private void apagar() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        for(int cont=1;cont<=3;cont++){
            String query = ("DELETE FROM tb_ponto WHERE id="+cont);    
            PreparedStatement preparedStmt = bd.prepareStatement(query);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd);        
        reiniciar_ai();
    }
    
    private void reiniciar_ai() throws SQLException{
        
        Connection bd = Tela_Inicial.getConnection();
        String query = ("alter table tb_ponto AUTO_INCREMENT = 1");    
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt.execute();
        Tela_Inicial.closeConnection(bd);        
        salvar_bd();
    }
    
    private void salvar_bd() throws SQLException{
        String pontuacao[]= new String[3];
        
        pontuacao[0]=listening.getText();
        pontuacao[1]=reading.getText();
        pontuacao[2]=grammar.getText();
        
        Connection bd = Tela_Inicial.getConnection();
        String query = "insert into tb_pontos (senha) values (?)";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        for(int cont=0;cont<3;cont++){
            preparedStmt.setString (1, pontuacao[cont]);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd); 
        JOptionPane.showMessageDialog(this,"Salvo com sucesso.","Salvamento",JOptionPane.INFORMATION_MESSAGE);
        salvar_finalizar.setText("Finalizar");
        cont++;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Alterar_pontos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Alterar_pontos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField grammar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField listening;
    private javax.swing.JButton nao_salvar;
    private javax.swing.JTextField reading;
    private javax.swing.JButton salvar_finalizar;
    // End of variables declaration//GEN-END:variables

    private Connection getConnection() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
