/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static proeficiencia.Tela_Inicial.getConnection;
/**
 *
 * @author mathe
 */
public class Tela_LogInAluno extends javax.swing.JFrame {
    int cont =0;
    String registro;
    String aluno="aluno", RA_atual;
    public Tela_LogInAluno() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Turma = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        RA = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Ano1 = new javax.swing.JRadioButton();
        Ano2 = new javax.swing.JRadioButton();
        Ano3 = new javax.swing.JRadioButton();
        terminar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Informações do aluno");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel1.setText("Escreva seu RA (Número de matrícula):");

        RA.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        RA.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                RAFocusLost(evt);
            }
        });
        RA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                RAKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                RAKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selecione a sua turma");
        jLabel2.setToolTipText("");

        Turma.add(Ano1);
        Ano1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Ano1.setText("1º Ano");

        Turma.add(Ano2);
        Ano2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Ano2.setText("2º Ano");

        Turma.add(Ano3);
        Ano3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        Ano3.setText("3º Ano");

        terminar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        terminar.setText("Terminar");
        terminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminarActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Voltar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RA)
                        .addComponent(Ano1))
                    .addComponent(jLabel2)
                    .addComponent(Ano2)
                    .addComponent(Ano3)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(terminar, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RA, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ano1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ano2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Ano3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terminar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void turma(){

            int serie;
            if(Ano1.isSelected()){
                serie=1;
            }
            else if(Ano2.isSelected()){
                serie=2;
            }
            else{
                serie=3;
            }
            File arquivo2 = new File("Informacoes_do_aluno.txt");
            try{
                FileWriter write= new FileWriter(arquivo2);
                PrintWriter escrever = new PrintWriter(write);
                escrever.println(registro);
                escrever.println(serie);
                escrever.close();
                write.close();

            }catch(IOException ex){
            }
            if(Ano1.isSelected()){
                PrimeiroAno a = new PrimeiroAno();
                a.setVisible(true);
                this.setVisible(false);
            }
            else if(Ano2.isSelected()){
                JOptionPane.showMessageDialog(this,"Esta aba ainda está incompleta.","Alerta",JOptionPane.ERROR_MESSAGE);
            }
            else{
                JOptionPane.showMessageDialog(this,"Esta aba ainda está incompleta.","Alerta",JOptionPane.ERROR_MESSAGE);
            }            
        
        
    }
    private void terminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminarActionPerformed

        try {
            verificador();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_LogInAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_terminarActionPerformed
    private void verificador () throws SQLException{
        RA_atual=RA.getText();
        
        Connection bd = Tela_Inicial.getConnection();

        String query;
        bd = getConnection();
        query = "SELECT * FROM tb_resultado";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt = bd.prepareStatement(query);
        ResultSet rs = preparedStmt.executeQuery();
        
        while(!RA_atual.equals(aluno) & rs.next()){ 
            aluno=rs.getString("ra");
        }

        rs.close();
	preparedStmt.close();
        Tela_Inicial.closeConnection(bd);
        
        
        registro=RA.getText();
        if(registro.equals("")&!Ano1.isSelected()&&!Ano2.isSelected()&&!Ano3.isSelected()){
            JOptionPane.showMessageDialog(this,"Você deve preencher o seu RA e escolher a sua turma para prosseguir","Alerta",JOptionPane.ERROR_MESSAGE);
        }
        else{
            if(registro.equalsIgnoreCase("")){
                JOptionPane.showMessageDialog(this,"Você deve preencher o seu RA para prosseguir","Alerta",JOptionPane.ERROR_MESSAGE); 
            }
            else if(!Ano1.isSelected()&&!Ano2.isSelected()&&!Ano3.isSelected()){
                JOptionPane.showMessageDialog(this,"Você deve selecionar sua turma antes de prosseguir","Alerta",JOptionPane.ERROR_MESSAGE); 
            }
            else{
                if(RA_atual.equals(aluno)){
                JOptionPane.showMessageDialog(this,"Você não pode refazer a prova.","Alerta",JOptionPane.ERROR_MESSAGE);
                }
                else{
                    cont++;
                    if(cont==1){
                        JOptionPane.showMessageDialog(rootPane,"Clique novamente no botão se seus dados estiverem certos, não será possível alterar depois.");
                    }
                    else{
                        turma();
                    }
                }
                
            }            
        }
    }
    private void RAKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RAKeyReleased
        RA.setText(RA.getText().replaceAll("[^0-9]", ""));
    }//GEN-LAST:event_RAKeyReleased

    private void RAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_RAKeyTyped
        int limite=7;
        if(RA.getText().length()>=limite){
          evt.consume();
        }
    }//GEN-LAST:event_RAKeyTyped

    private void RAFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_RAFocusLost
        cont=0;
        //Isto é feito para exibir novamente a mensagem de confirmação ao usuário ao finalizar seus dados
    }//GEN-LAST:event_RAFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        reiniciar_respostas_listening();
    }//GEN-LAST:event_formWindowOpened

    private void reiniciar_respostas_listening(){
        File arquivo = new File("RespostaDoAlunoNoListening.txt");
        try{
            FileWriter write= new FileWriter(arquivo);
            PrintWriter escrever = new PrintWriter(write);
            escrever.println("0");
            escrever.close();
            write.close();

        }catch(IOException ex){

        }       
        desbloquear_listening();
    }
    private void desbloquear_listening(){
        File arquivo=new File("Terminou_o_listening.txt");
        try{
            FileWriter write = new FileWriter(arquivo);
            PrintWriter escrever = new PrintWriter(write);
            escrever.println("nao");
            escrever.close();
            write.close();
        }
        catch(IOException ex){
            
        }
        reiniciar_resposta_reading();
    }
    private void reiniciar_resposta_reading(){
        File arquivo = new File("RespostaDoAlunoNoReading.txt");
        try{
            FileWriter write= new FileWriter(arquivo);
            PrintWriter escrever = new PrintWriter(write);
            escrever.println("0");
            escrever.close();
            write.close();

        }catch(IOException ex){

        }   
        desbloquear_reading();
    }
    private void desbloquear_reading(){
        File arquivo=new File("Terminou_o_reading.txt");
        try{
            FileWriter write = new FileWriter(arquivo);
            PrintWriter escrever = new PrintWriter(write);
            escrever.println("nao");
            escrever.close();
            write.close();
        }
        catch(IOException ex){
            
        }
        reiniciar_resposta_grammar();
    }
    private void reiniciar_resposta_grammar(){
        File arquivo = new File("RespostaDoAlunoNoGrammar.txt");
        try{
            FileWriter write= new FileWriter(arquivo);
            PrintWriter escrever = new PrintWriter(write);
            escrever.println("0");
            escrever.close();
            write.close();

        }catch(IOException ex){

        }   
        desbloquear_grammar();
    }
    private void desbloquear_grammar(){
        File arquivo=new File("Terminou_o_grammar.txt");
        try{
            FileWriter write = new FileWriter(arquivo);
            PrintWriter escrever = new PrintWriter(write);
            escrever.println("nao");
            escrever.close();
            write.close();
        }
        catch(IOException ex){
            
        }
    }
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Tela_Inicial abrir = new Tela_Inicial();
        abrir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_LogInAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_LogInAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_LogInAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_LogInAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_LogInAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Ano1;
    private javax.swing.JRadioButton Ano2;
    private javax.swing.JRadioButton Ano3;
    private javax.swing.JTextField RA;
    private javax.swing.ButtonGroup Turma;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton terminar;
    // End of variables declaration//GEN-END:variables
}
