/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;


import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class Tela_de_alterar_a_senha extends javax.swing.JFrame {
    String senha[]= new String [3];
    int verificador=0; 
    /**
     * Creates new form Tela_de_alterar_a_senha
     */
    public Tela_de_alterar_a_senha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        s1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        s2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        s3 = new javax.swing.JTextField();
        Salvar_e_finalizar = new javax.swing.JButton();
        Sair_sem_salvar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setText("Sua senha número 1:");

        s1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s1.setText("Carregando");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel2.setText("Sua senha número 2:");

        s2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s2.setText("Carregando");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel3.setText("Sua senha número 3:");

        s3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        s3.setText("Carregando");

        Salvar_e_finalizar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Salvar_e_finalizar.setText("Salvar");
        Salvar_e_finalizar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                Salvar_e_finalizarFocusLost(evt);
            }
        });
        Salvar_e_finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Salvar_e_finalizarActionPerformed(evt);
            }
        });

        Sair_sem_salvar.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Sair_sem_salvar.setText("Sair sem salvar");
        Sair_sem_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair_sem_salvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(s3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Sair_sem_salvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 159, Short.MAX_VALUE)
                        .addComponent(Salvar_e_finalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(s2)
                    .addComponent(s1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(s2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(s3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar_e_finalizar)
                    .addComponent(Sair_sem_salvar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void apagar() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        for(int cont=1;cont<=3;cont++){
            String query = ("DELETE FROM tb_senha WHERE id="+cont);    
            PreparedStatement preparedStmt = bd.prepareStatement(query);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd);        
        reiniciar_ai();
        
    }
    
    private void reiniciar_ai() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = ("alter table tb_senha AUTO_INCREMENT = 1");    
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt.execute();
        Tela_Inicial.closeConnection(bd);        
        salvar_bd();
    }
    
    private void salvar_bd() throws SQLException{
        Connection bd = Tela_Inicial.getConnection();
        String query = "insert into tb_senha (senha) values (?)";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        for(int cont=0;cont<3;cont++){
            preparedStmt.setString (1, senha[cont]);
            preparedStmt.execute();
        }
        Tela_Inicial.closeConnection(bd); 
        
        JOptionPane.showMessageDialog(rootPane,"Salvo com sucesso!");
        Salvar_e_finalizar.setText("Finalizar");

    }

    private void Salvar_e_finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Salvar_e_finalizarActionPerformed
        if(verificador==0){
            senha[0]=s1.getText();
            senha[1]=s2.getText();
            senha[2]=s3.getText();
            
            
            try {
                apagar();
            } catch (SQLException ex) {
                Logger.getLogger(Tela_de_alterar_a_senha.class.getName()).log(Level.SEVERE, null, ex);
            }
            verificador=1;
        }
        else{
            Tela_Area_do_professor abrir= new Tela_Area_do_professor();
            abrir.setVisible(true);
            this.setVisible(false);
        }

    }//GEN-LAST:event_Salvar_e_finalizarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            pegar_bd();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_de_alterar_a_senha.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_formWindowOpened
    
    private void pegar_bd() throws SQLException{
        String []senhasSalva= new String [3];
        Connection bd = Tela_Inicial.getConnection();
        int cont=0;
        String query;
        query = "SELECT * FROM tb_senha";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt = bd.prepareStatement(query);
        ResultSet rs = preparedStmt.executeQuery();
        while(rs.next()){ 
            senhasSalva[cont]=rs.getString("senha");
            cont++;
        }

        rs.close();
	preparedStmt.close();
        Tela_Inicial.closeConnection(bd);
        s1.setText(senhasSalva[0]);
        s2.setText(senhasSalva[1]);
        s3.setText(senhasSalva[2]);
          
    }
    
    private void Sair_sem_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair_sem_salvarActionPerformed
        Tela_Area_do_professor abrir= new Tela_Area_do_professor();
        abrir.setVisible(true);
        this.setVisible(false);
 
    }//GEN-LAST:event_Sair_sem_salvarActionPerformed

    private void Salvar_e_finalizarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_Salvar_e_finalizarFocusLost
        verificador=0;
        Salvar_e_finalizar.setText("Salvar");
    }//GEN-LAST:event_Salvar_e_finalizarFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_de_alterar_a_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_de_alterar_a_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_de_alterar_a_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_de_alterar_a_senha.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_de_alterar_a_senha().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair_sem_salvar;
    private javax.swing.JButton Salvar_e_finalizar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField s1;
    private javax.swing.JTextField s2;
    private javax.swing.JTextField s3;
    // End of variables declaration//GEN-END:variables
}
