/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proeficiencia;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mathe
 */
public class Tela_Grammar_Primeiro_Ano extends javax.swing.JFrame {
    String questoes[]= new String [11];
    String respostas[]= new String [10];
    /**
     * Creates new form Grammar_Primeiro_Ano
     */
    public Tela_Grammar_Primeiro_Ano() {
        initComponents();
    }
    private static final String DRIVER = "com.mysql.jdbc.Driver";
    private static final String URL = "jdbc:mysql://200.18.128.52:3306/matheuspeixoto";
    private static final String USER = "matheuspeixoto";
    private static final String PASS = "matheuspeixoto";
    
    public static Connection getConnection(){
        try {
            Class.forName(DRIVER);
            return DriverManager.getConnection(URL, USER, PASS);
        } catch (ClassNotFoundException | SQLException ex) {
            throw new RuntimeException("Erro na conexão", ex);
        }
    }
    
    public static void closeConnection(Connection con){
        if(con != null){
            try {
                con.close();
            } catch (SQLException ex) {
                System.err.println("Erro: "+ex);
            }
        } 
    }    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enunciado = new javax.swing.JLabel();
        finalizar = new javax.swing.JButton();
        Q1 = new javax.swing.JLabel();
        R1 = new javax.swing.JTextField();
        Q2 = new javax.swing.JLabel();
        R2 = new javax.swing.JTextField();
        Q3 = new javax.swing.JLabel();
        R3 = new javax.swing.JTextField();
        Q4 = new javax.swing.JLabel();
        R4 = new javax.swing.JTextField();
        Q5 = new javax.swing.JLabel();
        R5 = new javax.swing.JTextField();
        Q6 = new javax.swing.JLabel();
        R6 = new javax.swing.JTextField();
        Q7 = new javax.swing.JLabel();
        R7 = new javax.swing.JTextField();
        Q8 = new javax.swing.JLabel();
        R8 = new javax.swing.JTextField();
        Q9 = new javax.swing.JLabel();
        R9 = new javax.swing.JTextField();
        Q10 = new javax.swing.JLabel();
        R10 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        enunciado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        enunciado.setText("Carregando");

        finalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        finalizar.setText("Finalizar");
        finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finalizarActionPerformed(evt);
            }
        });

        Q1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q1.setText("Carregando");

        R1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q2.setText("Carregando");

        R2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q3.setText("Carregando");

        R3.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q4.setText("Carregando");

        R4.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q5.setText("Carregando");

        R5.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q6.setText("Carregando");

        R6.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q7.setText("Carregando");

        R7.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q8.setText("Carregando");

        R8.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q9.setText("Carregando");

        R9.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        Q10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        Q10.setText("Carregando");

        R10.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(375, 375, 375)
                        .addComponent(finalizar))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(enunciado, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                            .addComponent(Q1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R4, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R5, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R6, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R7, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R8, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(R9, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Q10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
                            .addComponent(R10, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(enunciado)
                .addGap(18, 18, 18)
                .addComponent(Q1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Q10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(R10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addComponent(finalizar)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void finalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finalizarActionPerformed
        
        respostas[0]=R1.getText();
        respostas[1]=R2.getText();
        respostas[2]=R3.getText();
        respostas[3]=R4.getText();
        respostas[4]=R5.getText();
        respostas[5]=R6.getText();
        respostas[6]=R7.getText();
        respostas[7]=R8.getText();
        respostas[8]=R9.getText();
        respostas[9]=R10.getText();
        
        if(respostas[0].equalsIgnoreCase("") || respostas[1].equals("") || respostas[2].equals("") || respostas[3].equals("") || respostas[4].equals("") || respostas[5].equals("") || respostas[6].equals("") || respostas[7].equals("") || respostas[8].equals("") || respostas[9].equals("") ){
            JOptionPane.showMessageDialog(this,"Você não respondeu alguma questão.","Alerta",JOptionPane.ERROR_MESSAGE);
        }
        else{
            salvar_resposta_do_aluno();
        }
        

    }//GEN-LAST:event_finalizarActionPerformed
    
    private void salvar_resposta_do_aluno(){
        File arquivo = new File("RespostaDoAlunoNoGrammar.txt");
        try{
            
            FileWriter write= new FileWriter(arquivo);
            PrintWriter escrever = new PrintWriter(write);
            for(int cont=0;cont<10;cont++){
                escrever.println(respostas[cont]);
            }
            escrever.close();
            write.close();

        }catch(IOException ex){

        }

        concluiu();
    }
    private void concluiu (){

        File arquivo_bloqueio=new File("Terminou_o_grammar.txt");
        try{
            FileWriter write = new FileWriter(arquivo_bloqueio);
            PrintWriter escrever = new PrintWriter(write);
            escrever.println("terminou");
            escrever.close();
            write.close();
        }
        catch(IOException ex){
            
        }
        PrimeiroAno abrir= new PrimeiroAno();
        abrir.setVisible(true);
        this.setVisible(false);
    }
    
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        try {
            pegar_questoes_bd();
        } catch (SQLException ex) {
            Logger.getLogger(Tela_Grammar_Primeiro_Ano.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formWindowOpened


    private void pegar_questoes_bd() throws SQLException {
        Connection bd = Tela_Inicial.getConnection();
        int cont=0;
        String query;
        
        query = "SELECT * FROM tb_grammar_primeiro_ano";
        PreparedStatement preparedStmt = bd.prepareStatement(query);
        preparedStmt = bd.prepareStatement(query);
        ResultSet rs = preparedStmt.executeQuery();
        while(rs.next()){ 
            if(cont<11){
                questoes[cont]=rs.getString("questoes_respostas");
                cont++;
            }
        }
        rs.close();
	preparedStmt.close();
        Tela_Inicial.closeConnection(bd);
        arrumar_questoes();
    }
    private void arrumar_questoes(){
        enunciado.setText(questoes[0]);
        Q1.setText(questoes[1]);
        Q2.setText(questoes[2]);
        Q3.setText(questoes[3]);
        Q4.setText(questoes[4]);
        Q5.setText(questoes[5]);
        Q6.setText(questoes[6]);
        Q7.setText(questoes[7]);
        Q8.setText(questoes[8]);
        Q9.setText(questoes[9]);
        Q10.setText(questoes[10]);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Grammar_Primeiro_Ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Grammar_Primeiro_Ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Grammar_Primeiro_Ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Grammar_Primeiro_Ano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Grammar_Primeiro_Ano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Q1;
    private javax.swing.JLabel Q10;
    private javax.swing.JLabel Q2;
    private javax.swing.JLabel Q3;
    private javax.swing.JLabel Q4;
    private javax.swing.JLabel Q5;
    private javax.swing.JLabel Q6;
    private javax.swing.JLabel Q7;
    private javax.swing.JLabel Q8;
    private javax.swing.JLabel Q9;
    private javax.swing.JTextField R1;
    private javax.swing.JTextField R10;
    private javax.swing.JTextField R2;
    private javax.swing.JTextField R3;
    private javax.swing.JTextField R4;
    private javax.swing.JTextField R5;
    private javax.swing.JTextField R6;
    private javax.swing.JTextField R7;
    private javax.swing.JTextField R8;
    private javax.swing.JTextField R9;
    private javax.swing.JLabel enunciado;
    private javax.swing.JButton finalizar;
    // End of variables declaration//GEN-END:variables
}
